runtime: custom
env: flex
# runtime: nodejs16

# instance_class: F2

# env_variables:
#   URI : '<MONGO_URI>'
#   PORT : 8080

# handlers:
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

